# Tenzin Choetso
# Chapter 11 question 11-10

def dict_words ():
    """ returns words from words.txt in a dictionary
    with words as keys"""
    d = dict()
    fin = open('words.txt')
    for line in fin:
        word = line.strip().lower()
        d[word] = word
    return d

def rotate_word(a,b):
    """Rotates a word by n places.

       a : string
       b : integer

       Returns: string"""
    final = ""
    for letter in a:
        ordletter = ord(letter)
        upperend = 123
        lowerend = 97
     
        new_ordletter = (ordletter + b) % upperend
        if new_ordletter < lowerend :
               new_ordletter += lowerend
               final += chr(new_ordletter)
        else:
            final += chr (new_ordletter)

    return final
def rotate_word(a,b):
    """Rotates a word by n places.

       a : string
       b : integer

       Returns: string"""
    final = ""
    for letter in a:
        ordletter = ord(letter)
        upperend = 123
        lowerend = 97
     
        new_ordletter = (ordletter + b) % upperend
        if new_ordletter < lowerend :
               new_ordletter += lowerend
               final += chr(new_ordletter)
        else:
            final += chr (new_ordletter)

    return final
def rotate_word(a,b):
    """Rotates a word by n places.

       a : string
       b : integer

       Returns: string"""
    final = ""
    for letter in a:
        ordletter = ord(letter)
        upperend = 123
        lowerend = 97
     
        new_ordletter = (ordletter + b) % upperend
        if new_ordletter < lowerend :
               new_ordletter += lowerend
               final += chr(new_ordletter)
        else:
            final += chr (new_ordletter)

    return final

def rotate_pairs(word,dict_word):
    """Prints all words in 'words.text' that 
    can be generated by rotating word.
    word: string
    dict_word: dictionary with words as keys"""
    for i in range(1,14):
        for key in word:
             rotate= rotate_word(key,i)
             if rotate in word:
                 print key, i,rotate_word(key,i)
w = dict_words()
rotate_pairs(w, 13)






